config/routes.rb
Luxola::Application.routes.draw do
  resources :product_lists

  root 'product_lists#index'

end

app/models/product_list.rb
class ProductList < ActiveRecord::Base
	validates :name, presence: true
	validates :name, length: { minimum: 3}
	validates :description, length: {minimum: 5}
	validates :price, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/product_lists_controller.rb
class ProductListsController < ApplicationController
  before_action :set_product_list, only: [:show, :edit, :update, :destroy]

  # GET /product_lists
  # GET /product_lists.json
  def index
    @product_lists = ProductList.all
  end

  # GET /product_lists/1
  # GET /product_lists/1.json
  def show
  end

  # GET /product_lists/new
  def new
    @product_list = ProductList.new
  end

  # GET /product_lists/1/edit
  def edit
  end

  # POST /product_lists
  # POST /product_lists.json
  def create
    @product_list = ProductList.new(product_list_params)

    respond_to do |format|
      if @product_list.save
        format.html { redirect_to @product_list, notice: 'Product list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @product_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_lists/1
  # PATCH/PUT /product_lists/1.json
  def update
    respond_to do |format|
      if @product_list.update(product_list_params)
        format.html { redirect_to @product_list, notice: 'Product list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_lists/1
  # DELETE /product_lists/1.json
  def destroy
    @product_list.destroy
    respond_to do |format|
      format.html { redirect_to product_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_list
      @product_list = ProductList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_list_params
      params.require(:product_list).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_lists_helper.rb
module ProductListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luxola</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Luxola Product List</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/product_lists">products</a></li>
      </ul>
    </div>
  </div>
</nav>

<footer>
  <div class="container">
    <font color="grey">YeonJu Mok Product List 2014</font>
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/product_lists/_form.html.erb
<%= form_for(@product_list) do |f| %>
  <% if @product_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_list.errors.count, "error") %> prohibited this product_list from being saved:</h2>

      <ul>
      <% @product_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_lists/edit.html.erb
<h1>Editing product_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_list %> |
<%= link_to 'Back', product_lists_path %>

app/views/product_lists/index.html.erb
<h1>My Product</h1>

<table>
  <thead>
  <col width="100">
  <col width="135">
  <col width="110">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @product_lists.each do |product_list| %>
      <tr id="<%= dom_id(product_list) %>">
        <td><%= product_list.name %></td>
        <td><%= product_list.description %></td>
        <td><%= product_list.price %></td>
        <td><%= link_to 'Show', product_list %></td>
        <td><%= link_to 'Edit', edit_product_list_path(product_list) %></td>
        <td><%= link_to 'Destroy', product_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product list', new_product_list_path %>

app/views/product_lists/new.html.erb
<h1>New product_list</h1>

<%= render 'form' %>

<%= link_to 'Back', product_lists_path %>

app/views/product_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product_list.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product_list.price %>
</p>

<%= link_to 'Edit', edit_product_list_path(@product_list) %> |
<%= link_to 'Back', product_lists_path %>